#SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
spring:
  profiles:
    # Load our own Spring Security filter chain without LDAP
    active: integrationTest
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  kafka:
    consumer:
      # Setting this property to "earliest" prevents failing integration tests caused
      # by the producer sending a message before the consumer has been assigned the topic/partition.
      # When not set it defaults to "latest"
      auto-offset-reset: earliest
      group-id: "gxf-sng-crest-device-service"

# port for proxy, using mutual TLS
server:
  port: 9000

config:
  # port for web client
  web-server:
    port: 9001
    authorized-roles: "kod"

kafka:
  consumers:
    pre-shared-key:
      topic: "pre-shared-key"
    command:
      topic: "command"
  producers:
    device-message:
      topic: "crest-message"
    command-feedback:
      topic: "command-feedback"
    firmware:
      topic: "firmware"
      key: "firmware"

database:
  encryption-key: "super-secret-key"
psk:
  decryption:
    method: "RSA"
    private-key:
      1: |-
        -----BEGIN PRIVATE KEY-----
        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCNHqJp9izMQQQu0hL+yy/U4VjUy82Om0FNd16yUfIjgvITIF6WavffpR9RZRoDxE2h7lJAVu1kIQqUtDOPlLMzUDDYkd2gLhnG+wROoJLFuyhg5lI1iVVfBH/5gTHlRckmvELylvG03pD9sUqcfbSTVl/uWhH/LkwezP39AadDjhor4EpolZShGqzNlToA3aw2v+a9HsqD7MbbHd2DVfjpc4V9U51HILXIE71xY5lIqJCUYUu/uuRXLVFpMG33Jaj1ySe6UDvUPD/OxuzRDlEziiKbinOtkRE1ot/Oq95a3IRXsEPZ/+CANuJKfgUbLnEn2MAkku+MaBbAvwPYp8HP7+A7GlwR5mI9ivT/50nwMYcYWosCZn40phY0U5fhWWR6srH2d52mbW2BAsyGB1imbc2heIzKkNP/Xc/+T2uO62wlnPpgHs0E4LnA2kelrU3QxC0ErZbAj694byVaHZpplCxYpOrammShTYtli/g3UK3ZyDuUwhesAltFVga97xJoQySLN7arw9haHYW7Y1mRchQ/pBMd1bjeDOjViecN9hHCURLtFEJEDBW92sJIwqZPFjFlMaftGe2LNa83mW34/FNsxqXShUDmg6wlBQDwgkJWvTRcSsh2ofitcGW5xEdWm1EMWyc30nd9ddh3GQVIR2CYe10JfYwbkc/PwfubPQIDAQABAoICABsUZdYvhykq0MKrTTnXg7Y2B/XNpgRXhpB295UAZJar6ggBjiUPIcGozfmwjO1sHfmU4fO2upccQAuJCNvkjP6rxLPKSd0S+59TS+BKr9+Bqp3tlJjxYZB6LJSUVh7I5XCpb69dh8RNcUU9YDPna19ak84JOqrdF35Rl+uVBaPRAPSqdZzcF0lS9RX+LMM9xm47JOvlnLb0GLSzZm5tcPZbVKJYCTY88KUUJKY9lox6zEOs5/xCwM55w8WLpY5ni6SelSELhG+VoCjtw0Pam3poZ3uxdcE4tTS1rHzcPi7xYfPxvxN2Jn50CbiBtjkhEFW1IiniiFVJJBSYkwRgLLCRN1jfOqzBBcHVlnE1oh4HpeYqRFTUJDVcS0gC2YJxCT44tdYAuWjR2+0oB0Rjlk5ExF4TVWumK1DGQC1ENTh4Ms83UCGVy8lS01dXmVurVMAweW1BUpktfHoXTut8OKxWpgHHVZRYg/68utA6mLeP0vqD19sLElrHU81/O792sBaiaz4xyhgLkNAMk/llqTEU4sN6p8RgOCa3cJqBxzo4ytVLU529B7qzFJk6f63IY9I7ELnpuDEfoUxW68X9aFh3/Xyags+wAYJoiK/YlBYO2q4EznutbqLGSLIgRTUMVT9UMctFdxvkTm52aDsgb6z2FH93kqxPstwgOsDTfb+BAoIBAQDFdwVX5mpWaOWg44gwhV7XCv7Kn4vpFOF4C96fXx+GOITEVG02OrY+IhM8ci9OvdT1lgCUl6XN1r+7L3rVaTva4CdxijNYLq0FSRAbhoYHBzV/QiParregtXZrIKLQQVrUTTvnPJ4f7t125Yq8QIL/N3X0odXpuL8/EE5wNIkPAwPdOvbtTZg+tyuFS4r7GsVh9YNIVWcvf9Bvs9We/Fr1gh9vYRvmHst9z7o7yzL6eTAoW12/QhVhZgCb1aW/bMKy52TjlYUTZlsSKty38sBTiOtza+y808t7SUR3vuEEzZw1hnkVHWB9opzYLQIgsG7DuLIJ09DKWWlB1rN4Tjr7AoIBAQC288CzFFoiKX0jjHGbBAEyBJzQ2Jc2jPVeOxojlH8q32+z+4bXi8g4UU+63QRsf79UqZDGP2yBYb+adxP/fs81cm/1YqPcfnFKPvohbVouFYRdJjOokYK+VQyvzfEMxlGIIQ7KO62I8lxATk2sXCOIneozojyBdkGSyt3BzlMdoGIRMTiA9ZQOZQROiYnHTAN4l2ZtGZSdLIkQB7ASnepe6T4dcSTfNToghudNr0M3NQwPpgzFaI2gtD6Lrf0lRndrf84TR3bAUq3DWwFFz1sdcnruqIHgeTlhuqNqK/MZKLeZjgGJvEwGdBaVZBjyP7tuyAgSD/trj5sf9Id6j60nAoIBAE63JHUmz+sEQ82ABlE5SVY19t20/iP7A+pD6Qnk9H8f1qUg9qwweWeJU9u7tOoRuGvx0OdrEFheq+2lfrTGD2swAek76z3S1XwO5RHj7Vet4wCI0Bwjm+W/kKYhy2VzOA77fs6uFmaqZLQ5yrVCjjXI2Qec39YcpHgyOuJ1vtEyJX8yOy7byL3vbLTlKVDyGg7zvNK/4LNJo0B0Esse0++cYIWY03NHgVz0yst9NCQu3SipS1SrtjQuYj28zCbj5zVEEq66cuMJ4XH7jiLx7QMfyKQpOKUJVMsfqOCHQdIVWJjpsyjcnhNXGGkAgCGh03XIEYjjXA7d15y8RqzFmrMCggEAFmTj04fMOJ5HeRB533WwB8VUxKOebsj2R+CIJI7Kuh67d5Z0PPIZQfuB/OeM4RMKAnz3Aa1FxNiIMYod4opNJsepOKooUJcRmvr2dx0Bit6LYzOH4zxcepvCf8p/lQa5eCZDvzFq3nZ8IEr1awGkP9bEkilrqpUlFajLWCu/NMMq/du+hNqKkvB+hHaFbOW7DwnJOdWFwW9wH4wxWzYFODToq4Xr8356bPzWV0X6vkk5/rhem9NecqtddI+JiwSDHZ95RBbdTFFSf7UmBLuK9aHLtmbd7vInufS0iAx1J0E6qAsf2RI5ZBjVoterzgtLEBZgFoXqSpI7dL/jzXbExQKCAQBhfBBkTLqvyA84ylDLtkEJzEITHS+LJPsieKFLpvPQsV2IaZ9nLtxQhYdVOZmvVbOLJGugh2Y8AG8EeMm5bqoa/JObdChmt+GDnlDj2rla8dPdw/JHWlOq5xzsaXSWMGIykqURzM52wkZp3sOEe30RPrfo69Kn2sUzex4YmnnWZCQz5CHot7AqVS+e0jsYdvIp1JsRkJGYp+eecUBRa/+FmjyBGwONJ5GafXn6r9iDrsBoMOmYhzsSf4mVyR6htOZsbY2UKnmsNb2FxssgnHRXYiQtTuWuFIgz1EjTmBoKvDoQCb+A30jtaiaZhMRUzx8+kOP1o62YiVisrEwj1wpG
        -----END PRIVATE KEY-----
message:
  max-bytes: 1024

logging:
  level:
    com:
      alliander: info
    org:
      gxf: info
    root: warn
